# Generated by Django 2.2.5 on 2019-11-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20191106_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
