# Generated by Django 2.2.5 on 2019-11-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='estimated_pick_up_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
